### PR TITLE
fixed setinterval requestanimationframe sht lol

### PR DESCRIPTION
**Pull request by ZeroTixDev**
this way is much better

### CODE REVIEW

**Comment by NKY5223** [comment]
Okay I implemented this time to close :3

**Comment by NKY5223** [comment]
very gud :+1:

**Comment by NKY5223** [comment]
Sorry but Zero, why does this freeze the render?

**Comment by NKY5223** [comment]
Found the problem, if the data is null, which it is, it will break the rendering, throwing an error and no longer rendering ANYTHING.
Okay guess I have to fix render() to check for null

**Comment by NKY5223** [comment]
Found a fix, if !e then set e to a preset object (but why is calcFPS broken now?)

**Comment by ZeroTixDev** [comment]
is the broken code on the master branch?

**Comment by NKY5223** [comment]
? no

**Comment by ZeroTixDev** [comment]
then how can i find the bug!

**Comment by NKY5223** [comment]
okay ill push

**Comment by ZeroTixDev** [comment]
try putting it on a seperate branch tho

**Comment by NKY5223** [comment]
Okay done

**Pull request closed without merging**
