### PR TITLE
DONT ASK JUST PUSH

### PR DESCRIPTION
**Pull request by shrekdotcom**

### CODE REVIEW

**Comment by rayhanadev** [comment]
Lmao we're removing skins according to NKY so this wouldn't really matter :C.

**Comment by MegaMemerMata** [comment]
Dang, that sucks. Why is that? If it’s because of beggars, _I can take care of ‘em, boss._ (Just like read that last line in a Jersey accent for effect)

**Comment by NKY5223** [comment]
actually its because of a new system, ravel personally told me to remove em soon :)

**Comment by NKY5223** [comment]
also the email notifs showed the changed files lmao

**Comment by rayhanadev** [comment]
@NKY5223 you do realize that Ravel doesn't really care about your client and if you keep listening to him he's just going to make it worse, right?

**Comment by Mathletesv** [comment]
if he doesn't listen to him he'll just remove the client from the captcha and end it altogether xD

**Comment by rayhanadev** [comment]
@Mathletesv well at the rate things are going the only thing special about the client is slightly better speeds, different icons, and colors in the chat. Otherwise its same (even less) than the actual game.

**Pull request closed without merging**
