### PR TITLE
const controls = document.querySelector(".controls");

### PR DESCRIPTION
**Pull request by tritone246**

### CODE REVIEW

**Comment by NKY5223** [comment]
hmmm...

**Comment by NKY5223** [comment]
bruh why did you use a class instead of an id

**Comment by tritone246** [comment]
classes pro id sucks.
if u wanna use id go ahead im not gonna stop u

**Comment by NKY5223** [comment]
> classes pro id sucks.
> if u wanna use id go ahead im not gonna stop u

well uh... id is faster, and classes usually refer to a bunch of elements

**Comment by NKY5223** [comment]
welp this is too many commits behind :/

**Pull request closed without merging**
