### PR TITLE
Add RayhanADev/HayrenRyzm's Skin

### PR DESCRIPTION
**Pull request by rayhanadev**
Accidentally deleted my fork, created a new one with a smaller image :).

### CODE REVIEW

**Review by rayhanadev — COMMENTED** [review]
Looks good to me!

**Comment by rayhanadev** [comment]
Hey okay so am I allowed to prettify some of the CSS? It's really what I'm good at.

Some Examples:
* [my portfolio](https://rayhanadev.vercel.app) (check the css, the site is still a wip)
* [some docs I made](https://replapi-it-docs.vercel.app)
* [my custom viewcounter site](https://myviewcounts.rayhanadev.repl.co/)
* [not really css but it's game dev](https://crossyroadjs.rayhanadev.repl.co/)

**Review by rayhanadev — COMMENTED** [review]
Yep still works!

**Comment by NKY5223** [comment]
> Hey okay so am I allowed to prettify some of the CSS? It's really what I'm good at.
> 
> Some Examples:
> 
> * [my portfolio](https://rayhanadev.vercel.app) (check the css, the site is still a wip)
> * [some docs I made](https://replapi-it-docs.vercel.app)
> * [my custom viewcounter site](https://myviewcounts.rayhanadev.repl.co/)
> * [not really css but it's game dev](https://crossyroadjs.rayhanadev.repl.co/)

sure, uhhhh

**Comment by NKY5223** [comment]
do ya wanna just be a dev :/
i dont want another wave of "give me  a color name :(((

**Comment by rayhanadev** [comment]
@NKY5223 Like I really just need an dev "job" to be dedicated to xD. Any ideas you have I'd be down to implement!

Also are we in different timezones? (I'm UTC-6)

**Comment by NKY5223** [comment]
totally different timezone, im UTC+8 XD

**Comment by rayhanadev** [comment]
Lol hello from across the world xD

**Comment by rayhanadev** [comment]
So @NKY5223 what do you say, can I be a dev?

**Comment by NKY5223** [comment]
idk man what do ya wanna do???

**Comment by NKY5223** [comment]
btw skins r gonna b removed soon :(

**Comment by rayhanadev** [comment]
> idk man what do ya wanna do???

Well I obviously want to help, but only if you say yes (~~or else I feel bad lol~~)

> btw skins r gonna b removed soon :(

Hahahahhaha rip poor wolfie, zero, and frog lmao

Also I'm working on making that title screen look good ;D

**Pull request closed without merging**
